# Generated by Django 4.2.13 on 2024-07-12 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_published_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='realease_date',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
