# Generated by Django 4.2.13 on 2024-07-12 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_realease_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='realease_date',
            new_name='released_date',
        ),
    ]
